# Generated by Django 4.2.4 on 2023-09-29 09:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
